/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fcca;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Cheikh Mbacké
 */
public class ConsommationRegister extends javax.swing.JFrame {

    /**
     * Creates new form AbonneRegister
     */
    public ConsommationRegister(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        msg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        backLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ni = new javax.swing.JTextField();
        debut = new javax.swing.JTextField();
        fin = new javax.swing.JTextField();
        ai = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(7, 27, 87));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fcca/image/ic_account_circle_white_24dp.png"))); // NOI18N
        jLabel2.setText("Nouvel index");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 150, 35));

        jButton1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fcca/image/baseline_send_black_24dp.png"))); // NOI18N
        jButton1.setText("Enregistrer");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHideActionText(true);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, -1, 36));

        msg.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(msg, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 289, 24));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fcca/image/logo.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 0, -1, 563));

        exitLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(255, 255, 255));
        exitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fcca/image/baseline_close_white_24dp.png"))); // NOI18N
        exitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        jPanel1.add(exitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(848, 0, 42, 35));

        backLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backLabel.setForeground(new java.awt.Color(255, 255, 255));
        backLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fcca/image/baseline_arrow_back_white_24dp.png"))); // NOI18N
        backLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });
        jPanel1.add(backLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 42, 35));

        jLabel8.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fcca/image/baseline_offline_bolt_white_24dp2.png"))); // NOI18N
        jLabel8.setText("N°Compteur");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 132, 37));

        jComboBox.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBoxMouseEntered(evt);
            }
        });
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 289, 37));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fcca/image/compteur-electrique04.gif"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 250, 150));

        jLabel12.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fcca/image/baseline_date_range_white_24dp.png"))); // NOI18N
        jLabel12.setText("Date de début");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 150, 35));

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fcca/image/baseline_date_range_white_24dp.png"))); // NOI18N
        jLabel3.setText("Date de fin");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 150, 35));

        jLabel4.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fcca/image/ic_account_circle_white_24dp.png"))); // NOI18N
        jLabel4.setText("Ancien index");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 150, 35));

        ni.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        ni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                niKeyTyped(evt);
            }
        });
        jPanel1.add(ni, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 290, 40));

        debut.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(debut, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 290, 40));

        fin.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        jPanel1.add(fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 290, 40));

        ai.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        ai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aiKeyTyped(evt);
            }
        });
        jPanel1.add(ai, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 290, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fcca/image/baseline_cloud_download_black_24dp.png"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 170, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fcca/image/baseline_copyright_white_18dp.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 540, -1, -1));

        copyright.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        copyright.setForeground(new java.awt.Color(153, 153, 153));
        copyright.setText("Copyright (C) 2018 by Cheikh");
        jPanel1.add(copyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void errorMessage(String message,JLabel label){
            label.setText("");
            label.setText(message);
            label.setForeground(Color.red);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
             msg.setText("");
             String cpt; 
             String dateDebut=debut.getText();
             String dateFin=fin.getText();
             String AI= ai.getText();
             String NI=ni.getText();
                 try {
                     if(dateDebut.length()!=0 && dateFin.length()!=0 && AI.length()!=0 && NI.length()!=0 && 
                             !jComboBox.getSelectedItem().toString().equals("") && Integer.parseInt(AI)<Integer.parseInt(NI)){
                        cpt= jComboBox.getSelectedItem().toString();
                        Connection conn;
                        conn = ConnectBD.BD();
                        //Enregistrement d'une consommationn
                        Statement state=conn.createStatement();
                        ResultSet rst=state.executeQuery("SELECT idCompteur FROM compteur WHERE numCompteur='"+cpt+"'");
                        int idCpt=0;
                        while(rst.next())
                            idCpt=rst.getInt("idCompteur");
                        //Verifier si une comsommation a été déja enregistrée sur ce compteur
                        Statement st=conn.createStatement();
                        ResultSet rs=st.executeQuery("SELECT idCompteur FROM consommation");
                        Boolean existe=false;
                        while(rs.next()){
                                if(idCpt==rs.getInt("idCompteur"))
                                    existe=true;
                                    break;
                             }
                        if(existe){
                            Statement s=conn.createStatement();
                            ResultSet r=s.executeQuery("SELECT dateFin,NI From consommation WHERE idCompteur='"+idCpt+"'");
                            while(r.next()){
                                dateDebut=r.getString("dateFin");
                                AI=r.getString("NI");
                            }
                        }
                         
                        PreparedStatement ps=conn.prepareStatement("INSERT INTO consommation (dateDebut,dateFin,AI,"+
                            "NI,idCompteur) VALUES (?,?,?,?,?)");
                        //Verification du format de la date   
                         try {
                             ps.setDate(1, java.sql.Date.valueOf(dateDebut));
                             ps.setDate(2, java.sql.Date.valueOf(dateFin));
                         } catch (Exception e) {
                             JOptionPane.showMessageDialog(null, "La date doit être sous format aaaa-mm-jj");
                         }
                        
                        ps.setInt(3, Integer.parseInt(AI));
                        ps.setInt(4, Integer.parseInt(NI));
                        ps.setInt(5, idCpt);
                        ps.executeUpdate();
                        conn.close();
                        //message
                        JOptionPane.showMessageDialog(null, "Consommation enregistrée avec succés");
                        msg.setText("Enregistrement réussie");
                        msg.setForeground(Color.green);
                        debut.setText("");
                        fin.setText("");
                        ai.setText("");
                        ni.setText("");
                        }else{
                            errorMessage("Veuiller vérifier les champs", msg);
                     }
                 } catch (Exception e) {
                     JOptionPane.showMessageDialog(null, "Veuiller indiquer le numéro de compteur");
                 }
                 
             
    }//GEN-LAST:event_jButton1ActionPerformed
    public void isANumber(KeyEvent events,JLabel label){
          label.setText("");
        char c=events.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            events.consume();
            label.setText("Veuiller entrer des chiffres");
            label.setForeground(Color.red);
        }
    }
    @SuppressWarnings("empty-statement")
    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        // TODO add your handling code here:
               CloseFrame.close(exitLabel,this);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Dashboard().setVisible(true);
    }//GEN-LAST:event_backLabelMouseClicked

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        // TODO add your handling code here:
        
                
               
    }//GEN-LAST:event_jComboBoxActionPerformed

    private void jComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMouseClicked

    private void aiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aiKeyTyped
        // TODO add your handling code here:
        isANumber(evt, msg);
    }//GEN-LAST:event_aiKeyTyped

    private void niKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_niKeyTyped
        // TODO add your handling code here:
        isANumber(evt, msg);
    }//GEN-LAST:event_niKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jComboBox.removeAllItems();
        Connection conn;
        try {
            //Recuperation de tous les numéros de compteurs
            conn = ConnectBD.BD();
            Statement st=conn.createStatement();
            String sqlQuery="SELECT numCompteur,idAbonne FROM compteur WHERE idAbonne<>0";
            ResultSet rs=st.executeQuery(sqlQuery);

            while(rs.next()){
                jComboBox.addItem(rs.getString("numCompteur"));
            }
            if(!rs.first())
                JOptionPane.showMessageDialog(null, "Il n'ya plus d'abonnés dans la base");
            jButton2.setEnabled(false);
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(AbonneRegister.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMouseEntered

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Connection conn;
        try {
            //Recuperation de tous les numéros de compteurs
            conn = ConnectBD.BD();
            Statement st=conn.createStatement();
                String sqlQuery="SELECT numCompteur FROM compteur WHERE idAbonne<>0";
                ResultSet rs=st.executeQuery(sqlQuery);         
                
                while(rs.next()){
                    jComboBox.addItem(rs.getString("numCompteur"));
                }
                conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(AbonneRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsommationRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsommationRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsommationRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsommationRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsommationRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ai;
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel copyright;
    private javax.swing.JTextField debut;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JTextField fin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel msg;
    private javax.swing.JTextField ni;
    // End of variables declaration//GEN-END:variables
}
